# Generated by Django 5.1.3 on 2024-12-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionTardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lateapp.alumno')),
                ('comision1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_preferida', to='lateapp.comision')),
                ('comision2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_secundaria', to='lateapp.comision')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lateapp.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuatrimestre', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo', models.IntegerField()),
                ('inscriptos', models.IntegerField(default=0)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lateapp.comision')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lateapp.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('materia', 'comision'), name='unique_materia_comision')],
            },
        ),
    ]
